import Head from "next/head";
import Link from "next/link";

export default function About() {
  return (
    <>
      <Head>
        <title>about us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="x_JdDu9817rocm812pGlP9M81UyBwunEdQmlbzA3tO4" />
      </Head>
      <section>
        <div className="container">
          <div className="col-lg-10 m-auto">
            <h1>About Us</h1>
          </div>
        </div>
      </section>
    </>
  );
}