import Head from 'next/head'
import { Inter } from '@next/font/google'
import HeroSection from './Components/Herosection'
import HomeBlogList from './Components/HomeBlogList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="x_JdDu9817rocm812pGlP9M81UyBwunEdQmlbzA3tO4" />
      </Head>
      <div>
         <HeroSection/>
         <HomeBlogList/>
      </div>
    </>
  )
}
